name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

      - name: Archive the dist folder
        run: |
          tar -czf dist.tar.gz dist node_modules package.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          scp -o StrictHostKeyChecking=no dist.tar.gz ubuntu@107.23.137.107:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no ubuntu@107.23.137.107 << 'EOF'
            if [ ! -d "~/services/auth-service" ]; then
              mkdir -p ~/services/auth-service
            fi
            cd ~/services/auth-service
            rm -rf dist node_modules package.json
            tar -xzf /home/ubuntu/dist.tar.gz -C ~/services/auth-service
            
            echo "${{ secrets.ENV_FILE }}" > .env

            pm2 delete auth-service || true
            pm2 start npm --name "auth-service" -- run start:prod --prefix ~/services/auth-service --node-args="--max_old_space_size=2048" --update-env
          EOF
